version: "3.3"
services:
  database:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=crawler
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bbat
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
  export:
    build:
      context: .
      dockerfile: export/Dockerfile
    hostname: export
    restart: always
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_OPTIONS: --max-old-space-size=8192
      COOKIE_EXPORT_MONGO_COL: findings
      COOKIE_EXPORT_MONGO_HOST: mongo
      COOKIE_EXPORT_MONGO_POOLSIZE: 16
    command: sh -c "/wait && npm start"
  mongo:
    image: mongo:4.4
    hostname: mongo
    restart: always
    mem_reservation: 2g
    mem_limit: 4g
    expose:
      - "27017"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodata:/data/db

#networks:
#  default:

volumes:
  mongodata:
  mysqldata:
